spring.application.name=IA-API

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

secret-api-key=${OPEN_API_KEY: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}
